import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Sidebar } from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard Tailwind Master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className="overflow-y-hidden antialiased"
    >
      <body className={inter.className}>
        <div className="min-h-screen bg-white dark:bg-zinc-900 lg:grid lg:grid-cols-app">
          <Sidebar />

          <main className="max-h-screen overflow-y-scroll px-4 pb-12 pt-24 lg:col-start-2 lg:px-8 lg:pt-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
